<div class="jumbotron">
    <h1>Welcome to Simple Invoices</h1>

    <p>
        Congratulations! You have successfully installed the
        <a href="https://github.com/simpleinvoices2/simpleinvoices2" target="_blank">Simple Invoices</a>.
        You are currently running Simple Invoices version <?= \SimpleInvoices\Module::VERSION ?>.
        This is not a working copy as it is being developed and many of the features are missing.
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/simpleinvoices2/simpleinvoices2" target="_blank">Fork Simple invoices 2 on GitHub &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Follow Development</h3>
            </div>
            <div class="panel-body">
                <p>
                    Zend Framework is under active development. If you are
                    interested in following the development of SI, you can check
                    <a href="https://plus.google.com/communities/102476804981627142204">SI on Google Plus</a>,
                    and <a href="https://github.com/simpleinvoices2/simpleinvoices2/issues">SI2 issue tracker</a>
                    (link requires a GitHub account). This is a great resource
                    for staying up to date with the latest developments!
                </p>

                <p><a class="btn btn-success pull-right" href="http://github.com/simpleinvoices2/simpleinvoices2" target="_blank">SI2 on GitHub &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Discover Modules</h3>
            </div>
            <div class="panel-body">
                <p>
                    As the project is being ported to Zend Framework 3 you may
                    visit ZF community site serving as a repository and gallery 
                    for ZF modules. The project is available <a href="https://github.com/zendframework/modules.zendframework.com">on GitHub</a>.
                    The site is currently live and currently contains a list of
                    some of the modules already available for ZF.
                </p>

                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank">Explore ZF Modules &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Help &amp; Support</h3>
            </div>
            <div class="panel-body">
                <p>
                    Currentlly unsupported. Sorry.
                </p>
            </div>
        </div>
    </div>
</div>
