<div class="page-header">
	<h1>New Customer</h1>
</div>

<?php if ($this->error) : ?>
	<div class="alert alert-danger" role="alert">
		<strong>Error!</strong>
		The has been an error while trying to save the customer.
	</div>
<?php endif; ?>

<?php
 $form->setAttribute('action', $this->url('customers', ['action' => 'new']));
 $form->prepare();
 ?>

<?= $this->form()->openTag($form); ?>
    <div class="form-group">
    	<div class="row">
        	<div class="col-xs-12 col-sm-3 text-right text-left-xs">
            	<?= $this->formLabel($form->get('name')); ?>
            </div>
            <div class="col-xs-12 col-sm-6">
            	<?= $this->formElement($form->get('name')); ?>
            </div>
        </div>
    </div>
    
    <div class="form-group">
    	<div class="row">
        	<div class="col-xs-12 col-sm-3 text-right text-left-xs">
            	<?= $this->formLabel($form->get('street_address')); ?>
            </div>
            <div class="col-xs-12 col-sm-6">
            	<?= $this->formElement($form->get('street_address')); ?>
            </div>
        </div>
    </div>
    
    <div class="form-group">
    	<div class="row">
        	<div class="col-xs-12 col-sm-3 text-right text-left-xs">
            	<?= $this->formLabel($form->get('street_address2')); ?>
            </div>
            <div class="col-xs-12 col-sm-6">
            	<?= $this->formElement($form->get('street_address2')); ?>
            </div>
        </div>
    </div>
    
    <div class="form-group">
    	<div class="row">
        	<div class="col-xs-12 col-sm-3 text-right text-left-xs">
            	<?= $this->formLabel($form->get('city')); ?>
            </div>
            <div class="col-xs-12 col-sm-6">
            	<?= $this->formElement($form->get('city')); ?>
            </div>
        </div>
    </div>
    
    <div class="form-group">
    	<div class="row">
        	<div class="col-xs-12 col-sm-3 text-right text-left-xs">
            	<?= $this->formLabel($form->get('state')); ?>
            </div>
            <div class="col-xs-12 col-sm-6">
            	<?= $this->formElement($form->get('state')); ?>
            </div>
        </div>
    </div>
    
    <div class="form-group">
    	<div class="row">
        	<div class="col-xs-12 col-sm-3 text-right text-left-xs">
            	<?= $this->formLabel($form->get('zip_code')); ?>
            </div>
            <div class="col-xs-12 col-sm-6">
            	<?= $this->formElement($form->get('zip_code')); ?>
            </div>
        </div>
    </div>
    
    <div class="form-group">
    	<div class="row">
        	<div class="col-xs-12 col-sm-3 text-right text-left-xs">
            	<?= $this->formLabel($form->get('country')); ?>
            </div>
            <div class="col-xs-12 col-sm-6">
            	<?= $this->formElement($form->get('country')); ?>
            </div>
        </div>
    </div>
    
    <div class="form-group">
    	<div class="row">
        	<div class="col-xs-12 col-sm-3 text-right text-left-xs">
            	<?= $this->formLabel($form->get('phone')); ?>
            </div>
            <div class="col-xs-12 col-sm-6">
            	<?= $this->formElement($form->get('phone')); ?>
            </div>
        </div>
    </div>
    
    <div class="form-group">
    	<div class="row">
        	<div class="col-xs-12 col-sm-3 text-right text-left-xs">
            	<?= $this->formLabel($form->get('mobile_phone')); ?>
            </div>
            <div class="col-xs-12 col-sm-6">
            	<?= $this->formElement($form->get('mobile_phone')); ?>
            </div>
        </div>
    </div>
    
    <div class="form-group">
    	<div class="row">
        	<div class="col-xs-12 col-sm-3 text-right text-left-xs">
            	<?= $this->formLabel($form->get('fax')); ?>
            </div>
            <div class="col-xs-12 col-sm-6">
            	<?= $this->formElement($form->get('fax')); ?>
            </div>
        </div>
    </div>
    
    <div class="form-group">
    	<div class="row">
        	<div class="col-xs-12 col-sm-3 text-right text-left-xs">
            	<?= $this->formLabel($form->get('email')); ?>
            </div>
            <div class="col-xs-12 col-sm-6">
            	<?= $this->formElement($form->get('email')); ?>
            </div>
        </div>
    </div>
    
    <div class="form-group">
    	<div class="row">
        	<div class="col-xs-12 col-sm-3 text-right text-left-xs">
            	<?= $this->formLabel($form->get('comments')); ?>
            </div>
            <div class="col-xs-12 col-sm-6">
            	<?= $this->formElement($form->get('comments')); ?>
            </div>
        </div>
    </div>
    
    <div class="form-group">
        <div class="row">
        	<div class="col-xs-12 col-sm-3 text-right text-left-xs">
            	<?= $this->formLabel($form->get('enabled')); ?>
            </div>
            <div class="col-xs-12 col-sm-6">
            	<?= $this->formElement($form->get('enabled')); ?>
            </div>
        </div>
    </div>
    
    <?= $this->formRow($form->get('id')); ?>                     
    <?= $this->formRow($form->get('csrf')); ?>
    
    
    <a href="<?= $this->url('customers') ?>" class="btn btn-lg btn-link" role="button">Cancel</a>
    <?= $this->formSubmit($form->get('submit')); ?>
<?= $this->form()->closeTag(); ?>
