<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Simple Invoices')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'])
                 ->prependStylesheet($this->basePath('assets/font-awesome/css/font-awesome.min.css'))
                 ->prependStylesheet($this->basePath('assets/bootstrap/dist/css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <?= $this->content ?>
        
        <?= $this->inlineScript() 
                 ->prependFile($this->basePath('assets/bootstrap/dist/js/bootstrap.min.js'))
                 ->prependFile($this->basePath('assets/jquery/dist/jquery.min.js'))
        ?>
    </body>
</html>
