<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Simple Invoices')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'])
                 ->prependStylesheet($this->basePath('css/layout.css'))
                 ->prependStylesheet($this->basePath('assets/trumbowyg/dist/ui/trumbowyg.min.css'))
                 ->prependStylesheet($this->basePath('assets/font-awesome/css/font-awesome.min.css'))
                 ->prependStylesheet($this->basePath('assets/bootstrap/dist/css/bootstrap.min.css'))
                 ->prependStylesheet($this->basePath('css/docs.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <span style="color:#ffffff;">Simple</span><strong style="color: #FFA500;">Invoices</strong>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <?= $this->navigation('Zend\Navigation\Default')
                             ->menu()
                             ->setMinDepth(0)
                             ->setMaxDepth(1)
                             ->setUlClass('nav navbar-nav')
                             ->setPartial('partial/navigation.phtml');
                    ?>
                    <?= $this->navigation('Zend\Navigation\Secondary')
                             ->menu()
                             ->setMinDepth(0)
                             ->setMaxDepth(1)
                             ->setUlClass('nav navbar-nav navbar-right')
                             ->setPartial('partial/navigation.phtml');
                    ?>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
            	<p>Thank you for invoicing with Simple Invoices.</p>
            </footer>
        </div>
        <?= $this->inlineScript()
                 ->prependFile($this->basePath('assets/trumbowyg/dist/trumbowyg.min.js'))
                 ->prependFile($this->basePath('assets/bootstrap/dist/js/bootstrap.min.js'))
                 ->prependFile($this->basePath('assets/jquery/dist/jquery.min.js'))
        ?>
        <script>
        $('textarea').trumbowyg({
            btns: [
                ['viewHTML'],
                'btnGrp-semantic',
                ['link'],
                'btnGrp-justify',
                'btnGrp-lists',
                ['removeformat'],
                ['fullscreen']
            ]
        });
        </script>
    </body>
</html>
