<?php
/**
 * http://azmind.com/demo/bootstrap-login-forms/form-2/index.html
 */
$this->headLink()->appendStylesheet($this->basePath('css/login.css'))
                 ->appendStylesheet('http://fonts.googleapis.com/css?family=Roboto:400,100,300,500');

 $form->setAttribute('action', $this->url('login'));
 $form->prepare();
 ?>
 <div class="top-content">
     <div class="inner-bg">
     	<div class="container">
     	    <div class="row">
     	        <div class="col-sm-8 col-sm-offset-2 text">
                    <h1>Simple <strong>Invoices</strong></h1>
                    <div class="description">
                        <p>
                            Making invoicing rock since '05.
                        </p>
                    </div>
                </div>
     	    </div>
     		<div class="row">
                 <div class="col-sm-6 col-sm-offset-3 form-box">
                 	<div class="form-top">
                 	    <div class="form-top-left">
                            <h3>Login to our site</h3>
                            <p>Enter your username and password to log on:</p>
                        </div>
                        <div class="form-top-right">
                            <i class="fa fa-lock"></i>
                        </div>
                 	</div>
                 	<div class="form-bottom">
                 	     <?= $this->form()->openTag($form); ?>
                             <div class="form-group">
                                <?= $this->formLabel($form->get('username')); ?>
                             	<?= $this->formElement($form->get('username')); ?>
                             </div>
                             <div class="form-group">
                                 <?= $this->formLabel($form->get('password')); ?>
                                 <?= $this->formElement($form->get('password')); ?>
                            </div>
                            
                             <?= $this->formRow($form->get('csrf')); ?>
                             <?= $this->formSubmit($form->get('submit')); ?>
                         <?= $this->form()->closeTag(); ?>
                     </div>
                 </div>
             </div>
        </div>
    </div>
</div>